#ifndef BMP_CONSTANTS
#define BMP_CONSTANTS

#define HEADER_BYTES_COUNT 54
#define HEADER_IMAGE_SIZE_INDEX 34
#define HEADER_WIDTH_INDEX 18
#define HEADER_HEIGHT_INDEX 22

#endif // !BMP_CONSTANTS

